language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
script:
    - php -l pricewaiter.php
    - vendor/bin/phpcs --standard=PrestashopCodingstandard pricewaiter.php
install:
    - composer require konafets/prestashop-codingstandard:@dev
