language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
script:
    - php -l pricewaiter.php
    - vendor/bin/phpcs --standard=Prestashop pricewaiter.php
install:
    - composer require squizlabs/php_codesniffer
    - git clone https://github.com/PrestaShop/PrestaShop-norm-validator.git vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/Prestashop
